### ISSUE TITLE
launch-link anchors aren't present in the new redesign

### ISSUE THREAD

**Issue by MridulS** [econ-ark/econ-ark.org#23]
This doesn't seem to work now https://econ-ark.org/materials/blanchardpa2019#launch

**Comment by MridulS** [comment]
fixed with https://github.com/econ-ark/econ-ark.org/pull/27, https://github.com/econ-ark/econ-ark.org/pull/28

**Comment by llorracc** [comment]
@MridulS,

I spent quite a while trying to figure out why 

https://econ-ark.org/materials/BufferStockTheory#launch

didn't work.  Turns out that, even though BufferStockTheory.ipynb is what's in the markdown file, the launch url is REQUIRED to be all lower case.  Would it be easy to make it case-insensitive?

**Comment by MridulS** [comment]
Unfortunately no, GitHub Pages URL are case sensitive by design. There could be some hacks around (with redirection) to make this work but URLs are supposed to be case sensitive.

**Comment by llorracc** [comment]
Well, what is confusing is that info in the source documents and the GitHub names are case sensitive:  BufferStockTheory or whatever.  (See the BufferStockTheory.md file).  But the launch url only works if the user knows that for some reason that should be translated to all lower case.  

I see two options:

0.  We should make the metadata in the markdown files match the case of what econ-ark.org translates it to
     * This would just involve editing the .md files
     * But would it also involve a requirement that we rename the master files accordingly?  I really don't like bufferstocktheory without any capitals.
1. We could make econ-ark.org test for the presence of either docs whose names (case-sensitively) match the names in the Markdown .md metadata files, OR for an all-lower-case version of the same name, and to work if either exists.

The current approach of having names like BufferStockTheory in the .md file, and having a url that works only if that is translated to bufferstocktheory (lower case), but with no way for anyone to guess that, seems like a bad combination.

**Comment by llorracc** [comment]
@MridulS,

Would appreciate your input on these options: 

1. Fix the metadata so it matches what econ-ark.org translates it to
2. Fix econ-ark.org so it respects the capitalization of the metadata
3. Fix econ-ark.org so it will work with either choice (auto-downcased or original case-sensitive).  

I confess that I'm more enthusiastic about 2 or 3 than about 1.  But even 1. is better than the way we are doing it now.
