### ISSUE TITLE
BUG: https://econ-ark.org/materials/ does not work

### ISSUE THREAD

**Issue by alanlujan91** [econ-ark/econ-ark.org#60]
https://econ-ark.org/materials without the last forward slash does work. 

However, the home page redirects to https://econ-ark.org/materials/ which is a 404.

**Comment by DrDrij** [comment]
The required change to solve the issue was in the front matter of the page to change:
from `permalink: materials` `permalink: /materials/`

The _config.yml file will take care of redirection to the page, eg. '/materials' or '/materials/'
